<basevalue 表号="00400" 中文名="基准值" 类别库="基础数据" 类="basevalue">
//  标识  英文标识  中文名称  基准值  单位
@  id    code      name      value   unit
</basevalue>

<basevoltage 表号="00401" 中文名="电压类型" 类别库="基础数据" 类="basevoltage">
//  标识  英文标识  中文名称  电压基准值  电压类型颜色  阻抗基值  电流基值  电压上限  电压下限  电压考核基值  功率考核基值  CA分析方式  总有功出力  总无功出力  总有功负荷  总无功负荷  总有功损耗  总无功损耗  模型所属区域  rdf标示  模型同步标识    是否参与无功电压统计  是否统计网损  下装分区       
@  id    code      name      nomvol      vlcolor       zbase     ibase     hvol      lvol      vbase_kh      sbase_kh      n1_manner   pgen        qgen        pload       qload       ploss       qloss       region_id     rdf_id   replicate_flag  bstatics              bloss         download_region
</basevoltage>

<company 表号="00403" 中文名="电力公司" 类别库="基础数据" 类="company">
//  标识  英文标识  中文名称  公司类型   有功发电  有功发电质量码  无功发电  无功发电质量码  有功负荷  有功负荷质量码  无功负荷  无功负荷质量码  有功损耗  有功损耗质量码  无功损耗  无功损耗质量码  有功厂用电  有功厂用电质量码  无功厂用电  无功厂用电质量码  电容器无功  电容器无功质量码  电抗器无功  电抗器无功质量码  有功净输出  有功净输出质量码  无功净输出  无功净输出质量码  用电有功  用电有功质量码  用电无功  用电无功质量码  统调用电有功  统调用电有功质量码  统调用电无功  统调用电无功质量码  统调发电有功  统调发电有功质量码  统调发电无功  统调发电无功质量码  网损率    网损率质量码   SubControlArea表首地址  rdf标示  模型所属区域  模型同步标识    是否参与无功电压统计  是否统计网损  下装分区       
@  id    code      name      cmpy_type  pgen      pgen_qual       qgen      qgen_qual       pload     pload_qual      qload     qload_qual      ploss     ploss_qual      qloss     qloss_qual      paux        paux_qual         qaux        qaux_qual         cap         cap_qual          reac        reac_qual         pint        pint_qual         qint        qint_qual         puse      pused_qual      quse      quse_qual       pdispt_use    pdispt_use_qual     qdispt_use    qdispt_use_qual     pdispt_gen    pdispt_gen_qual     qdispt_gen    qdispt_gen_qual     lossrate  lossrate_qual  oo_subcontrolarea       rdf_id   region_id     replicate_flag  bstatics              bloss         download_region
</company>

<subcontrolarea 表号="00404" 中文名="区域" 类别库="基础数据" 类="subcontrolarea">
//  标识  英文标识  中文名称  公司ID   父区域ID   有功发电  有功发电质量码  无功发电  无功发电质量码  有功负荷  有功负荷质量码  无功负荷  无功负荷质量码  有功损耗  有功损耗质量码  无功损耗  无功损耗质量码  有功厂用电  有功厂用电质量码  无功厂用电  无功厂用电质量码  电容器无功  电容器无功质量码  电抗器无功  电抗器无功质量码  有功净输出  有功净输出质量码  无功净输出  无功净输出质量码  用电有功  用电有功质量码  用电无功  用电无功质量码  统调用电有功  统调用电有功质量码  统调用电无功  统调用电无功质量码  统调发电有功  统调发电有功质量码  统调发电无功  统调发电无功质量码  网损率    网损率质量码   频率  频率质量码  SubStation表首地址  rdf标示  在线最大有功出力  在线最小有功出力  在线最大无功出力  在线最小无功出力  在线最大有功负荷  在线最小有功负荷  在线最大无功负荷  在线最小无功负荷  在线有功上旋转备用  在线无功上旋转备用  在线有功下旋转备用  在线无功下旋转备用  有功冷备出力  冷备负荷  应用附加表kid  区域类型   有功正旋备  有功负旋备  无功正备用  无功负备用  有功向上调节备用  有功向下调节备用  正快速备用容量  负快速备用容量  正时段备用   负时段备用   低压电抗投入容量  高压电抗投入容量  低压电容投入容量  CA分析方式  是否排除   事故备用  正时段备用2   负时段备用2   线路负载率    线路负载率质量码   变压器负载率  变压器负载率质量码  发电机负载率  发电机负载率质量码  越限断面个数         断面严重越限时间      断面严重越限次数       断面最大越限程度        平均AGC调节系数    AGC投运率     线路断面指标      变电站指标            发电备用指标          电压指标           频率指标             系统安全指标      系统质量指标       系统综合指标       平均旋转备用率  平均事故备用率  主网电压合格率  电压不合格次数  责任频率合格率  全网最高频率   全网最低频率   责任频率越限时间   母线数     停运母线数  变压器数  停运变压器数  变压器总容量  停运变压器容量  发电机数  停运发电机数  发电机总容量  停运发电机容量  线路数    停运线路数  500kV母线数  500kV停运母线数  220kV母线数  220kV停运母线数  500kV线路数  500kV停运线路数  220kV线路数  220kV停运线路数  是否外网区域  越限检验标志  模型所属区域  模型同步标识    小区号   负荷静特性模型类型  负荷静特性模型参数组  负荷动特性模型类型  负荷动特性模型参数组  感应电动机模型类型  感应电动机模型参数组  形成感应电动机负荷最小值  是否参与无功电压统计  是否统计网损  序列号       单位名称  检修编码  联系人   无功正冷备  下装分区         10min上调节备用  10min下调节备用  30min上调节备用  30min下调节备用  5分钟非旋转备用  10分钟非旋转备用  30分钟非旋转备用
@  id    code      name      cmpy_id  father_id  pgen      pgen_qual       qgen      qgen_qual       pload     pload_qual      qload     qload_qual      ploss     ploss_qual      qloss     qloss_qual      pplant      pplant_qual       qplant      qplant_qual       cap         cap_qual          reac        reac_qual         pint        pint_qual         qint        qint_qual         puse      pused_qual      quse      quse_qual       pdispt_use    pdispt_use_qual     qdispt_use    qdispt_use_qual     pdispt_gen    pdispt_gen_qual     qdispt_gen    qdispt_gen_qual     lossrate  lossrate_qual  freq  freq_qual   oo_substation       rdf_id   gnwmx             gnwmn             gnrmx             gnrmn             ldwmx             ldwmn             ldrmx             ldrmn             unrsvwu             unrsvru             unrsvwd             unrsvrd             gnwcold       ldwcold   auxkid         area_type  p_up        p_dn        q_up        q_dn        p_adjust_up       p_adjust_dn       p_hurry_up      p_hurry_dn      p_minute_up  p_minute_dn  q_lv_rea          q_hv_rea          q_lv_cap          n1_manner   remove_fg  sgby      p_minute_up2  p_minute_dn2  ln_load_rate  ln_load_rate_qual  tr_load_rate  tr_load_rate_qual   gn_load_rate  gn_load_rate_qual   limit_violation_sec  limit_violation_time  limit_violation_times  limit_violation_degree  agc_adjust_coeffi  agc_run_rate  ln_sec_indicator  substation_indicator  generating_indicator  voltage_indicator  frequency_indicator  safety_indicator  quality_indicator  general_indicator  rvsp_rate       avsp_rate       avdp_rate       avdp_num        frequency_rate  max_frequency  min_frequency  frequency_lv_time  bus_total  bus_off     tr_total  tr_off        tr_nom_total  tr_nom_off      gn_total  gn_off        gn_nom_total  gn_nom_off      ln_total  ln_off      bus_total_1  bus_off_1        bus_total_2  bus_off_2        ln_total_1   ln_off_1         ln_total_2   ln_off_2         if_out_net    chk_lmt       region_id     replicate_flag  zone_no  smode               smode_par             dmode               dmode_par             mmode               mmode_par             pmin                      bstatics              bloss         obj_dispidx  dwmc      bm        linkman  qgupcold    download_region  p_agc10min_up    p_agc10min_dn    p_agc30min_up    p_agc30min_dn    p_op5min_rv      p_op10min_rv      p_op30min_rv    
</subcontrolarea>

<substation 表号="00405" 中文名="厂站" 类别库="基础数据" 类="substation">
//  标识  英文标识  中文名称  最高电压类型ID  区域ID      厂站类型  厂站编号  厂站状态  接线图名称  是否自动旁路代  是否参与考核  是否参与状态估计  节点数  岛数     所属岛  记录所属应用  有功发电  有功发电质量码  无功发电  无功发电质量码  有功负荷  有功负荷质量码  无功负荷  无功负荷质量码  有功损耗  有功损耗质量码  无功损耗  无功损耗质量码  有功厂用电  有功厂用电质量码  无功厂用电  无功厂用电质量码  电容器无功  电容器无功质量码  电抗器无功  电抗器无功质量码  光字牌值1      光字牌值质量码1  光字牌值2      光字牌值质量码2  VoltageLevel表首地址  PowerTransformer表首地址  MeasPoint表首地址  MeasAnolog表首地址  rdf标示  X坐标   Y坐标   职责区     图形最后入库时间  最大旋转有功出力  最小旋转有功出力  最大旋转无功出力  最小旋转无功出力  厂站在线最小有功负荷  厂站在线最小有功负荷  厂站在线最大无功负荷  厂站冷备有功出力  厂站冷备有功出力  应用附加表kid  有功上旋转备用  无功上旋转备用  有功下旋转备用  无功下旋转备用  有功正旋备  有功负旋备  无功正备用  无功负备用  有功向上调节备用  有功向下调节备用  正快速备用容量  负快速备用容量  正时段备用   负时段备用   低压电抗投入容量  高压电抗投入容量  低压电容投入容量  厂站最大可调出力  厂站最小可调出力  事故备用  额定容量  区域ID(省)   是否参与局部统计      厂站量测质量  正时段备用2   负时段备用2   最小技术出力  特殊接线方式  责任区ID   量测类型   越限检验标志  描述       是否自动对端代  量测评分         频率     频率质量码    频率变化率  频率变化率质量码  模型所属区域  模型同步标识    lfo参与因子  lfo所属群  lfo是否中心  是否安装有FWK  控制站类型  小区号   序列号       检修编码  所属公司  电厂地址  投运日期  退役日期  电厂运行状态  拼音简称  分区ID1      分区ID2      越限光字牌值      越限光字牌状态   越限个数        异常光字牌值    异常光字牌状态  异常个数      事故光字牌值    事故光字牌状态  事故个数      告知光字牌值  告知光字牌状态  告知个数    变位光字牌值      变位光字牌状态   变位个数        五类信号告警值  五类信号告警状态  是否加入仿真计算  无功正冷备  一体化区域号    拼接所属区域  厂站封锁标志   下装分区         10min上调节备用  10min下调节备用  30min上调节备用  30min下调节备用  5分钟非旋转备用  10分钟非旋转备用  30分钟非旋转备用  是否参与拓扑
@  id    code      name      bv_id           subarea_id  st_type   st_no     status    graph_name  if_passby       if_exam       caculate_se       nodes   islands  island  record_app    pgen      pgen_qual       qgen      qgen_qual       pload     pload_qual      qload     qload_qual      ploss     ploss_qual      qloss     qloss_qual      paux        paux_qual         qaux        qaux_qual         cap         cap_qual          reac        reac_qual         light_value_1  light_qual_1     light_value_2  light_qual_2     oo_voltagelevel       oo_powertransformer       oo_measpoint       oo_measanolog       rdf_id   x_coor  y_coor  aor_value  last_graph_time   gnwmx             gnwmn             gnrmx             gnrmn             ldwmx                 ldwmn                 ldrmx                 gnwcold           ldwcold           auxkid         unrsvwu         unrsvru         unrsvwd         unrsvrd         p_up        p_dn        q_up        q_dn        p_adjust_up       p_adjust_dn       p_hurry_up      p_hurry_dn      p_minute_up  p_minute_dn  q_lv_rea          q_hv_rea          q_lv_cap          p_adjust_max      p_adjust_min      sgby      mvarate   subarea_id1  localstatistics_flag  meas_fg       p_minute_up2  p_minute_dn2  pmin_tech     mode_type     resp_area  da_option  chk_lmt       describeb  if_autoaside    meas_eval_score  w_f_val  w_f_val_qual  w_f_dft     w_f_dft_qual      region_id     replicate_flag  lfo_fact     lfo_clus   is_cntr      bfwk           fwk_type    zone_no  obj_dispidx  bm        ssgs      dcdz      tyrq      tyrq1     dcyxzt        name_py   divarea_id1  divarea_id2  over_limit_value  over_limit_qual  over_limit_num  abnormal_value  abnormal_qual   abnormal_num  accident_value  accident_qual   accident_num  notify_value  notify_qual     notify_num  deflection_value  deflection_qual  deflection_num  alarm_value     alarm_qual        issim             qgupcold    dist_region_id  area_name     fac_lock_flag  download_region  p_agc10min_up    p_agc10min_dn    p_agc30min_up    p_agc30min_dn    p_op5min_rv      p_op10min_rv      p_op30min_rv      if_topo     
</substation>

<breaker 表号="00407" 中文名="断路器" 类别库="交流设备" 类="交流断路器">
//  标识  英文标识  中文名称  描述       厂站ID  间隔ID  电压类型ID  电压等级ID  首端连接点号  末端连接点号  断路器类型  通常状态   拓扑着色  设备投产状态  拓扑节点  记录所属应用  是否事故     故障跳闸额定值  电流正常值  电压正常值  有功正常值  无功正常值  是否参予考核  人工设置标志  状态估计人工变位标志  遮断容量   变位次数  最大变位次数  事故变位次数  最大事故变位次数  双位延迟时间  三相延迟时间  遥信值  状态    计算前遥信值  遥信值时间  辅助节点遥信值  辅助节点遥信质量码  辅助节点遥信时间  有功值  有功质量码  计算前有功值  有功量测时间  有功量测屏蔽  有功量测权值  无功值  无功质量码  计算前无功值  无功量测时间  无功量测屏蔽  无功量测权值  电流值  电流质量码  计算前电流值  电流量测时间  电流量测屏蔽  电流量测权值  功率因数   功率因数质量码  A相电流幅值  A相电流质量码  计算前A相电流值  A相电流相角  A相电流相角状态  A相电流量测时间  B相电流幅值  B相电流质量码  计算前B相电流值  B相电流相角  B相电流相角状态  B相电流量测时间  C相电流幅值  C相电流质量码  计算前C相电流值  C相电流相角  C相电流相角状态  C相电流量测时间  遥信值2      遥信质量码2  遥信值时间2  辅节点遥信值2     辅节点遥信质量码2  辅节点遥信值时间2  遥信值3      遥信质量码3  遥信值时间3  辅节点遥信值3     辅节点遥信质量码3  辅节点遥信时间3  零序电流模值  零序电流相角  正序电流模值  正序电流相角  负序电流模值  负序电流相角  rdf标示  全开遥信值  全开状态  全开计算前遥信值  全开遥信时间  全开辅助节点遥信值  全开辅助节点遥信质量码  全开辅助节点遥信时间  全合遥信值  全合状态  全合计算前遥信值  全合遥信时间  全合辅助节点遥信值  全合辅助节点遥信质量码  全合辅助节点遥信时间  故障概率  
@  id    code      name      describeb  st_id   bay_id  bv_id       vl_id       ind           jnd           brk_type    nom_state  tpcolor   run_state     tpnd      record_app    if_accident  amprating       inom        vnom        pnom        qnom        if_exam       manual        manual_se             mvarating  bw_num    max_bw_num    sgbw_num      max_sgbw_num      delay_time_1  delay_time_2  point   status  pnt_pre       pnt_time    vice_pnt_value  vice_pnt_qual       vice_pnt_time     p       p_qual      p_pre         p_time        p_notuse      p_weight      q       q_qual      q_pre         q_time        q_notuse      q_weight      i       i_qual      i_pre         i_time        i_notuse      i_weight      pw_factor  pw_factor_qual  i_a_value    i_a_qual       i_a_pre          i_a_angel    i_a_angle_bdfg   i_a_time         i_b_value    i_b_qual       i_b_pre          i_b_angel    i_b_angle_bdfg   i_b_time         i_c_value    i_c_qual       i_c_pre          i_c_angel    i_c_angle_bdfg   i_c_time         pnt_value_2  pnt_qual_2   pnt_time_2   vice_pnt_value_2  vice_pnt_qual_2    vice_pnt_time_2    pnt_value_3  pnt_qual_3   pnt_time_3   vice_pnt_value_3  vice_pnt_qual_3    vice_pnt_time_3  i0_m          angle_i0      i1_m          angle_i1      i2_m          angle_i2      rdf_id   point0      status0   pnt0_pre          point0_time   vice_pnt0_value     vice_pnt0_qual          vice_pnt0_time        point1      status1   pnt1_pre          point1_time   vice_pnt1_value     vice_pnt1_qual          vice_pnt1_time        fault_prob
</breaker>

<disconnector 表号="00408" 中文名="刀闸" 类别库="交流设备" 类="交流开关">
//  标识  英文标识  中文名称  描述       厂站ID  间隔ID  电压类型ID  电压等级ID  刀闸类型    通常状态   拓扑着色  设备投产状态  首端连接点号  末端连接点号  拓扑节点  记录所属应用  是否参予考核  人工设置标志  状态估计人工变位标志  双位延迟时间  三相延迟时间  遥信值  状态    计算前遥信值  遥信刷新时间  辅助节点遥信值  辅助节点遥信质量码  辅助节点遥信刷新时间  遥信值2      遥信质量码2  遥信刷新时间2  辅节点遥信值2     辅节点遥信质量码2  辅节点遥信刷新时间2  遥信值3      遥信质量码3  遥信刷新时间3  辅节点遥信值3     辅节点遥信质量码3  辅节点遥信刷新时间3  rdf标示  刀闸类型  应用附加表kid  责任区ID   模型所属区域  模型同步标识    序列号       拼音简称  调度许可权  调度管辖权  拼接所属区域  下装分区         全开遥信值  全开状态  全开计算前遥信值  全开遥信刷新时间  全开辅助节点遥信值  全开辅助节点遥信质量码  全开辅助节点遥信刷新时间  全合遥信值  全合状态  全合计算前遥信值  全合遥信刷新时间  全合辅助节点遥信值  全合辅助节点遥信质量码  全合辅助节点遥信刷新时间  故障概率  
@  id    code      name      describeb  st_id   bay_id  bv_id       vl_id       discr_type  nom_state  tpcolor   run_state     ind           jnd           tpnd      record_app    if_exam       manual        manual_se             delay_time_1  delay_time_2  point   status  pnt_pre       pnt_time      vice_pnt_value  vice_pnt_qual       vice_pnt_time         pnt_value_2  pnt_qual_2   pnt_time_2     vice_pnt_value_2  vice_pnt_qual_2    vice_pnt_time_2      pnt_value_3  pnt_qual_3   pnt_time_3     vice_pnt_value_3  vice_pnt_qual_3    vice_pnt_time_3      rdf_id   funtype   auxkid         resp_area  region_id     replicate_flag  obj_dispidx  name_py   ddxk        ddgx        area_name     download_region  point0      status0   pnt0_pre          pnt0_time         vice_pnt0_value     vice_pnt0_qual          vice_pnt0_time            point1      status1   pnt1_pre          pnt1_time         vice_pnt1_value     vice_pnt1_qual          vice_pnt1_time            fault_prob
</disconnector>

<grounddisconnector 表号="00409" 中文名="接地刀闸" 类别库="交流设备" 类="接地刀闸">
//  标识  英文标识  中文名称  描述       厂站ID  间隔ID  电压类型ID  电压等级ID  接地刀闸类型  通常状态   拓扑着色  设备投产状态  连接点号  拓扑节点  记录所属应用  是否参予考核  人工设置标志  状态估计人工变位标志  双位延迟时间  三相延迟时间  遥信值  状态    计算前遥信值  遥信刷新时间  辅助节点遥信值  辅助节点遥信质量码  辅助节点遥信刷新时间  遥信值2      遥信质量码2  遥信刷新时间2  辅节点遥信值2     辅节点遥信质量码2  辅节点遥信刷新时间2  遥信值3      遥信质量码3  遥信刷新时间3  辅节点遥信值3     辅节点遥信质量码3  辅节点遥信刷新时间3  rdf标示  责任区ID   模型所属区域  模型同步标识    序列号       拼音简称  调度管辖权  调度许可权  拼接所属区域  下装分区         全开遥信值  全开状态  全开计算前遥信值  全开遥信刷新时间  全开辅助节点遥信值  全开辅助节点遥信质量码  全开辅助节点遥信刷新时间  全合遥信值  全合状态  全合计算前遥信值  全合遥信刷新时间  全合辅助节点遥信值  全合辅助节点遥信质量码  全合辅助节点遥信刷新时间
@  id    code      name      describeb  st_id   bay_id  bv_id       vl_id       gddiscr_type  nom_state  tpcolor   run_state     nd        tpnd      record_app    if_exam       manual        manual_se             delay_time_1  delay_time_2  point   status  pnt_pre       pnt_time      vice_pnt_value  vice_pnt_qual       vice_pnt_time         pnt_value_2  pnt_qual_2   pnt_time_2     vice_pnt_value_2  vice_pnt_qual_2    vice_pnt_time_2      pnt_value_3  pnt_qual_3   pnt_time_3     vice_pnt_value_3  vice_pnt_qual_3    vice_pnt_time_3      rdf_id   resp_area  region_id     replicate_flag  obj_dispidx  name_py   ddgx        ddxk        area_name     download_region  point0      status0   pnt0_pre          pnt0_time         vice_pnt0_value     vice_pnt0_qual          vice_pnt0_time            point1      status1   pnt1_pre          pnt1_time         vice_pnt1_value     vice_pnt1_qual          vice_pnt1_time          
</grounddisconnector>

<busbarsection 表号="00410" 中文名="母线" 类别库="交流设备" 类="交流母线">
//  标识  英文标识  中文名称  描述       厂站ID  间隔ID  电压类型ID  电压等级ID  连接点号  状态    母线类型  拓扑着色  设备投产状态  拓扑节点  记录所属应用  越限检验标志  是否参予考核  电压设定值  电压上限  电压下限  电压正常值  线电压Uab  线电压质量码  计算前线电压幅值  线电压Uab时间  电压量测屏蔽  电压量测权值  相角  相角质量码  计算前电压相角  相角时间  相角量测屏蔽  相角量测权值  频率  频率质量码  频率时间  线电压Ubc  线电压质量码2  线电压Ubc时间  线电压Uca  线电压质量码3  线电压Uca时间  A相电压幅值  A相电压幅值质量码  计算前A相电压幅值  A相电压时间  B相电压幅值  B相电压幅值质量码  计算前B相电压幅值  B相电压时间  C相电压幅值  C相电压幅值质量码  计算前C相电压幅值  C相电压时间  rdf标示  故障概率  
@  id    code      name      describeb  st_id   bay_id  bv_id       vl_id       nd        status  bs_type   tpcolor   run_state     tpnd      record_app    chk_lim       if_exam       v_set       v_max     v_min     v_nom       v          v_qual        v_pre             v_time         v_notuse      v_weight      ang   ang_qual    ang_pre         ang_time  ang_notuse    ang_weight    f     f_qual      f_time    v_bc       v_bc_qual      v_bc_time      v_ca       v_ca_qual      v_ca_time      v_a          v_a_qual           v_a_pre            v_a_time     v_b          v_b_qual           v_b_pre            v_b_time     v_c          v_c_qual           v_c_pre            v_c_time     rdf_id   fault_prob
</busbarsection>

<generatingunit 表号="00411" 中文名="发电机组" 类别库="交流设备" 类="交流电源">
//  标识  英文标识  中文名称  描述       厂站ID  电压类型ID  电压等级ID  连接点号  状态    投运状态   发电机类型  拓扑着色  拓扑节点  记录所属应用  等值位置  越限检验标志  是否scd可控  是否参予考核  电流上限   额定电压  额定容量  上升速率  下降速率  机组无功上限  机组无功下限  机组有功上限  机组有功下限  正常有功功率  正常功率因数  正常无功功率  电压上限  电压下限  高端电压  PV控高端电压  节点类型  参与有功调节  有功分配系数  无功分配系数  调节节点号  调节母线号  目标电压值  厂用电范围参数1  厂用电范围参数2  有功厂用电百分比1  有功厂用电百分比2  有功厂用电百分比3  无功厂用电百分比1  无功厂用电百分比2  无功厂用电百分比3  有功厂用电  无功厂用电  厂用电率  厂用电功率因数  单位发电成本  煤耗特性系数0  煤耗特性系数1  煤耗特性系数2  调频特性系数  调节范围  网损修正系数  是否开断标志  接入电网电压类型ID  平衡机号  rdf标示  有功功率  有功质量码  计算前有功值  有功量测时间  有功量测屏蔽  有功量测权值  无功功率  无功质量码  计算前无功值  无功量测时间  无功量测屏蔽  无功量测权值  电流值  电流质量码  计算前电流值  电流量测时间  电流量测屏蔽  电流量测权值  电压值  电压质量码  计算前电压值  电压量测时间  电压量测屏蔽  电压量测权值  机端电压相角  机端电压相角质量码  相角量测时间  A相电流幅值  A相电流幅值质量码  A相电流量测时间  B相电流幅值  B相电流幅值质量码  B相电流量测时间  C相电流幅值  C相电流幅值质量码  C相电流量测时间  A相电压  A相电压质量码  A相电压计算前值  A相电压时间  A相电压屏蔽  A相电压权值  B相电压  B相电压质量码  B相电压计算前值  B相电压时间  B相电压屏蔽  B相电压权值  C相电压  C相电压质量码  C相电压计算前值  C相电压时间  C相电压屏蔽  C相电压权值  A相电压角度  A相电压角度质量码  A相电压角度计算前值  A相电压角度时间  A相电压角度屏蔽  A相电压角度权值  B相电压角度  B相电压角度质量码  B相电压角度计算前值  B相电压角度时间  B相电压角度屏蔽  B相电压角度权值  C相电压角度  C相电压角度质量码  C相电压角度计算前值  C相电压角度时间  C相电压角度屏蔽  C相电压角度权值  A相电流角度  A相电流角度质量码  A相电流角度计算前值  A相电流角度时间  A相电流角度屏蔽  A相电流角度权值  B相电流角度  B相电流角度质量码  B相电流角度计算前值  B相电流角度时间  B相电流角度屏蔽  B相电流角度权值  C相电流角度  C相电流角度质量码  C相电流角度计算前值  C相电流角度时间  C相电流角度屏蔽  C相电流角度权值  是否可调  有功设定值  无功设定值  电压设定值  电价     是否参与机组组合  是否参与日前组合  是否参与日内组合  是否参与实时组合  开机成本（元）  关机成本（元）  最小开机时间（h）  最小关机时间（h）  故障概率    预测偏差分布    预测偏差均值    预测偏差方差 
@  id    code      name      describeb  st_id   bv_id       vl_id       nd        status  run_state  gn_type     tpcolor   tpnd      record_app    position  chk_lim       in_scd       if_exam       amprating  kvnom     mvarate   rtnomup   rtnomdn   q_max         q_min         p_max         p_min         p_nom         pf            q_nom         v_max     v_min     v_high    pv_high       pf_type   p_agc         p_part        q_part        regind      regbs       vtarget     range1           range2           percent1           percent2           percent3           percentq1          percentq2          percentq3          paux        qaux        psa       psa_factor      cospu         cost0          cost1          cost2          frc           rgw       sloss         open_flag     bvh_id              slackun   rdf_id   p         p_qual      p_pre         p_time        p_notuse      p_weight      q         q_qual      q_pre         q_time        q_notuse      q_weight      i       i_qual      i_pre         i_time        i_notuse      i_weight      v       v_qual      v_pre         v_time        v_notuse      v_weight      ang           ang_qual            ang_time      i_a          i_a_qual           i_a_time         i_b          i_b_qual           i_b_time         i_c          i_c_qual           i_c_time         v_a      v_a_qual       v_a_pre          v_a_time     v_a_notuse   v_a_weigh    v_b      v_b_qual       v_b_pre          v_b_time     v_b_notuse   v_b_weigh    v_c      v_c_qual       v_c_pre          v_c_time     v_c_notuse   v_c_weigh    ang_va       ang_va_qual        ang_va_pre           ang_va_time      ang_va_notuse    ang_va_weigh     ang_vb       ang_vb_qual        ang_vb_pre           ang_vb_time      ang_vb_notuse    ang_vb_weigh     ang_vc       ang_vc_qual        ang_vc_pre           ang_vc_time      ang_vc_notuse    ang_vc_weigh     ang_ia       ang_ia_qual        ang_ia_pre           ang_ia_time      ang_ia_notuse    ang_ia_weigh     ang_ib       ang_ib_qual        ang_ib_pre           ang_ib_time      ang_ib_notuse    ang_ib_weigh     ang_ic       ang_ic_qual        ang_ic_pre           ang_ic_time      ang_ic_notuse    ang_ic_weigh     regable   p_set       q_set       v_set       p_price  uc_enable         da_enable         ro_enable         rt_enable         start_cost      stop_cost       min_open_time      min_close_time     fault_prob  fore_bias_dist  fore_bias_mean  fore_bias_var
</generatingunit>

<energyconsumer 表号="00412" 中文名="负荷" 类别库="交流设备" 类="交流负荷">
//  标识  英文标识  中文名称  描述       厂站ID  间隔ID  电压类型ID  电压等级ID  连接点号  状态    设备投产状态  负荷类型  拓扑着色  拓扑节点  记录所属应用  所在负荷区域  有功正常值  无功正常值  电流正常值  有功上限  无功上限  电流上限   是否参予考核  越限检验标志  等值连接位置  是否边界联络线  切负荷率  有功分配系数  无功分配系数  有功预测值  无功预测值  无功比例系数  是否开断标志  有功值  有功质量码  计算前有功值  有功量测时间  有功量测屏蔽  有功量测权值  无功值  无功质量码  计算前无功值  无功量测时间  无功量测屏蔽  无功量测权值  电流值  电流质量码  计算前电流值  电流量测时间  电流量测屏蔽  电流量测权值  A相电流值  A相电流质量码  A相电流量测时间  B相电流值  B相电流质量码  B相电流量测时间  C相电流值  C相电流质量码  C相电流量测时间  rdf标示  负荷有功下限  负荷无功下限  电压值  电压质量码  计算前电压值  电压量测时间  电压量测屏蔽  电压量测权值  有功设定值  无功设定值  是否可调  关联多能负荷  预测偏差分布    预测偏差均值    预测偏差方差   故障概率  
@  id    code      name      describeb  st_id   bay_id  bv_id       vl_id       nd        status  run_state     ld_type   tpcolor   tpnd      record_app    ld_area       p_nom       q_nom       i_nom       p_max     q_max     amprating  if_exam       chk_lim       position      if_bound        cutp      p_part        q_part        p_lf        q_lf        q_ratio       open_flag     p       p_qual      p_pre         p_time        p_notuse      p_weight      q       q_qual      q_pre         q_time        q_notuse      q_weight      i       i_qual      i_pre         i_time        i_notuse      i_weight      i_a        i_a_qual       i_a_time         i_b        i_b_qual       i_b_time         i_c        i_c_qual       i_c_time         rdf_id   p_min         q_min         v       v_qual      v_pre         v_time        v_notuse      v_weight      p_set       q_set       regable   imld          fore_bias_dist  fore_bias_mean  fore_bias_var  fault_prob
</energyconsumer>

<acline 表号="00413" 中文名="交流线路" 类别库="交流设备" 类="交流线路">
//  标识  英文标识  中文名称  描述       公司ID   区域ID      包含交流线段数  记录所属应用  rdf标示  责任区ID   模型所属区域  模型同步标识    拼接所属区域  下装分区       
@  id    code      name      describeb  cmpy_id  subarea_id  aclnseg_num     record_app    rdf_id   resp_area  region_id     replicate_flag  area_name     download_region
</acline>

<aclinesegment 表号="00414" 中文名="交流线段" 类别库="交流设备" 类="交流线路">
//  标识  英文标识  中文名称  描述       ist_id  二端厂站ID  线路ID     首段连接点号  末端连接点号  区域ID      电压类型ID  等值标志  状态    拓扑着色  设备投产状态  记录所属应用  电流上限   有功损耗  无功损耗  长度    线段类型ID号  充电标志  分段标志1   网损计算标志  是否SCD监视  分段标志2  自动等值参数来源  原始参数类型标志  正序电阻标幺值  正序电抗标幺值  正序电纳标幺值  零序电阻标幺值  零序电抗标幺值  零序电纳标幺值  正序电阻有名值  正序电抗有名值  正序电纳有名值  零序电阻有名值  零序电抗有名值  零序电纳有名值  正序电抗实测值  正序电导实测值  正序电纳实测值  rdf标示  功率限值  故障概率  
@  id    code      name      describeb  ist_id  jst_id      acline_id  ind           jnd           subarea_id  bv_id       eq_flag   status  tpcolor   run_state     record_app    amprating  ploss     qloss     length  type_id       charge    subsection  lossfg        in_scd       sec_flag   para_src          par_type          r_pu            x_pu            bch_pu          r0_pu           x0_pu           bch0_pu         r               x               bch             r0              x0              bch0            x_real          r_real          bch_real        rdf_id   smax      fault_prob
</aclinesegment>

<aclineend 表号="00415" 中文名="交流线段端点" 类别库="交流设备" 类="交流节点">
//  标识  英文标识  中文名称  描述       厂站ID  间隔ID  电压类型ID  电压等级ID  线段ID      连接点号  状态    拓扑着色  设备投产状态  拓扑节点  记录所属应用  是否参予考核  线路电压  是否开断标志  送端标志   有功功率  有功质量码  计算前有功  有功量测时间  有功量测屏蔽  有功量测权值  无功功率  无功质量码  计算前无功  无功量测时间  无功量测屏蔽  无功量测权值  电流值  电流质量码  计算前电流  电流量测时间  电流量测屏蔽  电流量测权值  电压值  电压质量码  计算前电压值  电压量测时间  电压量测屏蔽  电压量测权值  rdf标示
@  id    code      name      describeb  st_id   bay_id  bv_id       vl_id       aclnseg_id  nd        status  tpcolor   run_state     tpnd      record_app    if_exam       v_term    open_flag     send_flag  p         p_qual      p_pre       p_time        p_notuse      p_weight      q         q_qual      q_pre       q_time        q_notuse      q_weight      i       i_qual      i_pre       i_time        i_notuse      i_weight      v       v_qual      v_pre         v_time        v_notuse      v_weight      rdf_id 
</aclineend>

<powertransformer 表号="00416" 中文名="变压器" 类别库="交流设备" 类="双绕组变压器+三绕组变压器">
//  标识  英文标识  中文名称  描述       厂站ID  变压器类型  绕组类型   终端变标志  拓扑着色  状态    设备投产状态  记录所属应用  有功损耗  无功损耗  空载损耗(KW)  空载电流百分值  越限检验标志  rdf标示  故障概率    中性点拓扑节点  中性点物理节点编号
@  id    code      name      describeb  st_id   tr_type     wind_type  term        tpcolor   status  run_state     record_app    p_loss    q_loss    fix_loss      i_per           chk_lim       rdf_id   fault_prob  tpnd            knd               
</powertransformer>

<transformerwinding 表号="00417" 中文名="变压器绕组" 类别库="交流设备" 类="变压器绕组">
//  标识  英文标识  中文名称  描述       厂站ID  间隔ID  变压器ID  电压类型ID  电压等级ID  变压器绕组类型  拓扑着色  状态    设备投产状态  连接点号  中性点连接点号  拓扑节点  记录所属应用  分接头类型ID  有功上限  无功上限  变压器绕组连接类型  有载调压标志  绕组接地标志  绕组额定电压  绕组正常额定功率  额定电流   短路损耗  短路电压百分值  正序电阻标幺值  正序电抗标幺值  零序电阻标幺值  零序电抗标幺值  正序电阻有名值  正序电抗有名值  零序电阻有名值  零序电抗有名值  正序电阻实测值  正序电抗实测值  绕组接地电阻标幺值  绕组接地电抗标幺值  电导  电纳  变比(计算值)  是否开断标志  越限检验标志  绕组接地电阻有名值  绕组接地电抗有名值  有功功率  有功质量码  计算前有功值  有功量测时间  有功量测屏蔽  有功量测权值  无功功率  无功质量码  计算前无功值  无功量测时间  无功量测屏蔽  无功量测权值  电流值  电流质量码  计算前电流值  电流量测时间  电流量测屏蔽  电流量测权值  分接头位置  分接头质量码  计算前分接头位置  档位量测时间  分接头量测屏蔽  分接头量测权值  电压值  电压质量码  计算前电压值  电压量测时间  电压量测屏蔽  电压量测权值  电压下限  电压上限  rdf标示  激磁电导Gm  激磁电纳Bm
@  id    code      name      describeb  st_id   bay_id  tr_id     bv_id       vl_id       wind_type       tpcolor   status  run_state     nd        knd             tpnd      record_app    tapty_id      p_max     q_max     con_type            ltc_flag      ground_flag   kvnom         mvanom            amprating  pshort    vshort          r_pu            x_pu            r0_pu           x0_pu           r               x               r0              x0              r_real          x_real          rground_pu          xground_pu          g     b     t             open_flag     chk_lim       rground             xground             p         p_qual      p_pre         p_time        p_notuse      p_weight      q         q_qual      q_pre         q_time        q_notuse      q_weight      i       i_qual      i_pre         i_time        i_notuse      i_weight      tap         tap_qual      tap_pre           tap_time      tap_notuse      tap_weight      v       v_qual      v_pre         v_time        v_notuse      v_weight      v_min     v_max     rdf_id   gm          bm        
</transformerwinding>

<taptype 表号="00418" 中文名="变压器抽头类型" 类别库="基础数据" 类="taptype">
//  标识  英文标识  中文名称  最高档位  最低档位  额定档位  不变低档    不变高档    档位相移    档位电压变化量  rdf标示  责任区ID 
@  id    code      name      highstep  lowstep   nomstep   dn_nomstep  up_nomstep  step_phase  step            rdf_id   resp_area
</taptype>

<compensator_p 表号="00419" 中文名="并联电容/电抗器" 类别库="交流设备" 类="并联无功补偿装置">
//  标识  英文标识  中文名称  描述       厂站ID  间隔ID  电压类型ID  电压等级ID  连接点号  设备状态  设备投产状态  容抗器类型  拓扑着色  拓扑节点  记录所属应用  额定容量  额定电压  是否开断标志  连接线路名称  是否自动调压  无功值  无功质量码  计算前无功值  无功量测时间  无功量测屏蔽  无功量测权值  A相电流值  A相电流质量码  计算前A相电流值  A相电流量测时间  B相电流值  B相电流质量码  计算前B相电流值  B相电流量测时间  C相电流值  C相电流质量码  计算前C相电流值  C相电流量测时间  有功值  有功质量码  计算前有功值  有功量测时间  有功量测屏蔽  有功量测权值  正序电阻标幺值  正序电抗标幺值  所属容抗器组  零序电抗(pu)  可否自动投切  电容器投切次数限值  电容器实际投切次数  补偿线路ID  补偿线路名称  rdf标示  是否直流滤波器  故障概率    电压值  电压质量码  计算前电压值  电压量测时间  电压量测屏蔽  电压量测权值
@  id    code      name      describeb  st_id   bay_id  bv_id       vl_id       nd        status    run_state     cp_type     tpcolor   tpnd      record_app    mvarnom   kvnom     open_flag     position      if_avc        q       q_qual      q_pre         q_time        q_notuse      q_weight      i_a        i_a_qual       i_a_pre          i_a_time         i_b        i_b_qual       i_b_pre          i_b_time         i_c        i_c_qual       i_c_pre          i_c_time         p       p_qual      p_pre         p_time        p_notuse      p_weight      r_pu            x_pu            rc_groupno    x0            auto_set      auto_setlmt         auto_setnum         link_id     link_name     rdf_id   ishvdcfltr      fault_prob  v       v_qual      v_pre         v_time        v_notuse      v_weight    
</compensator_p>

<compensator_s 表号="00420" 中文名="串联补偿器" 类别库="交流设备" 类="串联无功补偿装置">
//  标识  英文标识  中文名称  描述       电压类型ID  电压等级ID  厂站ID  间隔ID  首端连接点号  末端连接点号  拓扑着色  设备状态  设备投产状态  首端拓扑节点  末端拓扑节点  记录所属应用  正序电阻  正序电抗  首端有功值  首端无功值  末端有功值  末端无功值  额定电流   运行电抗上限  运行电抗下限  额定电压值  额定功率  补偿线路ID  rdf标示  故障相别  故障类型  设备接地状态  应用附加表kid  设备整体运行状态  容抗类型  三端连接点号  三端拓扑节点  三端有功值  三端无功值  责任区ID   模型所属区域  模型同步标识    温度         虚节点名1   虚节点名2   虚节点名3   固定部分补偿度百分比  固定容抗有名值  固定容抗标幺值  固定串补控制模型参数组  可调部分补偿度百分比  容抗有名值  容抗标幺值  控制模型   可控串补控制模型参数组  分区ID      拼接所属区域  下装分区         故障概率  
@  id    code      name      describeb  bv_id       vl_id       st_id   bay_id  ind           jnd           tpcolor   status    run_state     itpnd         jtpnd         record_app    r         x         pi          qi          pj          qj          amprating  r_max         r_min         kvnom       mvarnom   line_id     rdf_id   fltphase  flttype   grdstatus     auxkid         grpstatus         cp_type   knd           ktpnd         pk          qk          resp_area  region_id     replicate_flag  temperature  busk1_name  busk2_name  busk3_name  comp_fix              xc_fix          xc_fixpu        cont_no_fix             comp_ctrl             xc_ctrl     xc_ctrlpu   cont_ctrl  cont_no_ctrl            divarea_id  area_name     download_region  fault_prob
</compensator_s>

<rectifierinverter 表号="00425" 中文名="换流器" 类别库="直流设备" 类="交直流变换器">
//  标识  英文标识  中文名称  厂站ID  直流系统ID  交流侧电压类型ID  直流侧电压类型ID  正极连接点号  负极连接点号  交流侧连接点号  极性      设备状态  设备投产状态  拓扑着色  交流拓扑节点  直流拓扑节点1  直流拓扑节点2  换流器桥数  换流变交流侧抽头类型ID  换流变阀侧抽头类型ID  换流变交流侧电压等级  换流变阀侧电压等级  换流器的铭牌直流电压  换流器额定功率  换流器最小功率  最小点火角  最大点火角  最小熄弧角  最大熄弧角  变压器的交流电阻  变压器的交流电抗  换相电抗  直流功率设定值  直流电流设定值  直流电压设定值  角度设定值  换流器控制方式  换流器降压运行电压  直流功率  直流功率质量码  直流功率计算前值  直流功率屏蔽  直流功率权重  直流电压  直流电压质量码  直流电压计算前值  直流电压屏蔽  直流电压权重  直流电流  直流电流质量码  电流计算前值   电流屏蔽  电流权重    换流变有功  换流变有功质量码  换流变有功计算前值  换流变有功屏蔽  换流变有功权重  换流变无功  换流变无功质量码  换流变无功计算前值  换流变无功屏蔽  换流变无功权重  换流变档位  换流变档位质量码  换流变档位计算前值  换流变档位屏蔽  换流变档位权重  角度值（控制角）  角度值质量码  角度值计算前值  角度值屏蔽  角度值权重  闭锁标志  闭锁标志质量码  闭锁标志计算前值  闭锁标志屏蔽  rdf标示  i侧换流变压器交流侧主抽头额定线电压(kV)  i侧换流变压器阀侧出口额定线电压(kV)  i侧每极换流桥数  i侧换流变压器单极总容量(MVA)  i侧换流变压器铜损电阻值(Ohm)  i侧换流变压器漏抗值(%)  i侧换流变压器最高抽头线电压(kV)  i侧换流变压器最低抽头线电压(kV)  i侧换流变压器抽头级数  j侧换流变压器交流侧主抽头额定线电压(kV)  j侧换流变压器阀侧出口额定线电压(kV)  j侧每极换流桥数  j侧换流变压器单极总容量(MVA)  j侧换流变压器铜损电阻值(Ohm)  j侧换流变压器漏抗值(%)  j侧换流变压器最高抽头线电压(kV)  j侧换流变压器最低抽头线电压(kV)  j侧换流变压器抽头级数  给定运行方式  给定极1点燃角(deg.)  给定极1熄弧角(deg.)  给定极2点燃角(deg.)  给定极2熄弧角(deg.)  告警方式  语音文件名  责任区ID   换流变交流侧分接头类型  换流变阀侧分接头类型  所属极性描述  模型所属区域  记录所属应用  模型同步标识    零序电压幅值  零序电压幅值质量码  零序电压角度  零序电压角度质量码  正序电压幅值  正序电压幅值质量码  正序电压角度  正序电压角度质量码  负序电压幅值  负序电压幅值质量码  负序电压角度  负序电压角度质量码  零序电流幅值  零序电流幅值质量码  零序电流角度  零序电流角度质量码  正序电流幅值  正序电流幅值质量码  正序电流角度  正序电流角度质量码  负序电流幅值  负序电流幅值质量码  负序电流角度  负序电流角度质量码  A相电压幅值  A相电压幅值质量码  A相电压角度  A相电压角度质量码  B相电压幅值  B相电压幅值质量码  B相电压角度  B相电压角度质量码  C相电压幅值  C相电压幅值质量码  C相电压角度  C相电压角度质量码  A相电流幅值  A相电流幅值质量码  B相电流幅值  B相电流幅值质量码  C相电流幅值  C相电流幅值质量码  A相电流角度  A相电流角度质量码  B相电流角度  B相电流角度质量码  C相电流角度  C相电流角度质量码  频率     频率质量码    频率变化率  频率变化率质量码  有功误差  有功误差质量码  无功误差  无功误差质量码  故障相别  故障类型  故障持续时间  故障位置  拼接所属区域  下装分区         故障概率  
@  id    code      name      st_id   dcsys_id    acbv_id           dcbv_id           idcnd         jdcnd         nd              polarity  status    run_state     tpcolor   tpnd          itpnd          jtpnd          nbridge     tapty_ac                tapty_dc              kvnom_ac              kvnom_dc            vdc_nom               pdc_nom         pdc_min         alpha_min   alpha_max   gamma_min   gamma_max   rxf               xxf               xc        pdc_set         idc_set         vdc_set         ang_set     ctl_mode        vdc_low             pdc       pdc_qual        dcp_value_pre     dcp_notuse    dcp_weight    vdc       vdc_qual        dcv_value_pre     v_notuse      dcv_weight    idc       idc_qual        dci_value_pre  i_notuse  dci_weight  pac         pac_qual          acp_value_pre       acp_notuse      acp_weight      qac         qac_qual          acq_value_pre       acq_notuse      acq_weight      tap         tap_qual          tap_value_pre       tap_notuse      tap_weight      ang               ang_qual      ang_value_pre   ang_notuse  ang_weight  block     block_qual      cf_value_pre      cf_notuse     rdf_id   vhi                                      vli                                  bi               sti                           rti                           xti                     vtimax                           vtimin                           ntapi                  vhj                                      vlj                                  bj               stj                           rtj                           xtj                     vtjmax                           vtjmin                           ntapj                  op            a10                  gam10                a20                  gam20                alarm_id  sound_name  resp_area  itapty                  ztapty                polename      region_id     record_app    replicate_flag  w_v0_mag      w_v0_mag_qual       w_v0_ang      w_v0_ang_qual       w_v1_mag      w_v1_mag_qual       w_v1_ang      w_v1_ang_qual       w_v2_mag      w_v2_mag_qual       w_v2_ang      w_v2_ang_qual       w_i0_mag      w_i0_mag_qual       w_i0_ang      w_i0_ang_qual       w_i1_mag      w_i1_mag_qual       w_i1_ang      w_i1_ang_qual       w_i2_mag      w_i2_mag_qual       w_i2_ang      w_i2_ang_qual       w_va_mag     w_va_mag_qual      w_va_ang     w_va_ang_qual      w_vb_mag     w_vb_mag_qual      w_vb_ang     w_vb_ang_qual      w_vc_mag     w_vc_mag_qual      w_vc_ang     w_vc_ang_qual      w_ia_mag     w_ia_mag_qual      w_ib_mag     w_ib_mag_qual      w_ic_mag     w_ic_mag_qual      w_ia_ang     w_ia_ang_qual      w_ib_ang     w_ib_ang_qual      w_ic_ang     w_ic_ang_qual      w_f_val  w_f_val_qual  w_f_dft     w_f_dft_qual      w_p_dif   w_p_dif_qual    w_q_dif   w_q_dif_qual    fltphase  flttype   fltkeeptm     fltpos    area_name     download_region  fault_prob
</rectifierinverter>

<dclinesegment 表号="00426" 中文名="直流线段" 类别库="直流设备" 类="直流支路">
//  标识  英文标识  中文名称  首段厂站ID  末端厂站ID  直流系统ID  电压类型ID  设备状态  投运状态   拓扑着色  允许载流量  正序串联电阻  rdf标示  单极直流线路电感(mH)  故障类型  应用附加表kid  设备整体运行状态  设备接地状态  责任区ID   模型所属区域  模型同步标识    序列号       拼音简称  调度管辖权  调度许可权  拼接所属区域  下装分区       
@  id    code      name      ist_id      jst_id      dcsys_id    bv_id       status    run_state  tpcolor   amprating   r             rdf_id   ll                    flttype   auxkid         grpstatus         grdstatus     resp_area  region_id     replicate_flag  obj_dispidx  name_py   ddgx        ddxk        area_name     download_region
</dclinesegment>

<dclineend 表号="00427" 中文名="直流线端" 类别库="直流设备" 类="直流节点">
//  标识  英文标识  中文名称  厂站ID  直流导线ID  连接点号  设备状态  投运状态   拓扑着色  拓扑节点  电压值  电压质量码  电压计算前值  电压屏蔽  电压权重  电流值  电流质量码  电流计算前值  电流屏蔽  电流权重  功率值  功率质量码  功率计算前值  功率屏蔽  功率权重  rdf标示  i侧接地引线电阻(Ohm)  i侧接地引线电感(mH)  j侧接地引线电阻(Ohm)  j侧接地引线电感(mH)  i侧接地极电阻(Ohm)  j侧接地极电阻(Ohm)  单极i侧平波电抗器电感(mH)  单极j侧平波电抗器电感(mH)  告警方式  语音文件名  负载率  负载率质量码  责任区ID   模型所属区域  电压类型ID  电压等级ID  模型同步标识    拼音简称  调度管辖权  调度许可权  序列号       拼接所属区域  下装分区       
@  id    code      name      st_id   dcln_id     nd        status    run_state  tpcolor   tpnd      vdc     vdc_qual    v_value_pre   v_notuse  v_weight  idc     idc_qual    i_value_pre   i_notuse  i_weight  pdc     pdc_qual    p_value_pre   p_notuse  p_weight  rdf_id   rpi                   lpi                  rpj                   lpj                  rei                 rej                 lsi                        lsj                        alarm_id  sound_name  i_rate  i_rate_qual   resp_area  region_id     bv_id       vl_id       replicate_flag  name_py   ddgx        ddxk        obj_dispidx  area_name     download_region
</dclineend>

<dcgroundterm 表号="00428" 中文名="直流接地端" 类别库="直流设备" 类="直流节点">
//  标识  英文标识  中文名称  连接点号  设备状态  投运状态   拓扑着色  拓扑节点  接地电阻  rdf标示  i侧交流母线补偿电容器滤波器单极容量(Mvar)  j侧交流母线补偿电容器滤波器单极容量(Mvar)  责任区ID   厂站ID  模型所属区域  模型同步标识    拼接所属区域  下装分区       
@  id    code      name      nd        status    run_state  tpcolor   tpnd      r         rdf_id   qci                                        qcj                                        resp_area  st_id   region_id     replicate_flag  area_name     download_region
</dcgroundterm>

<energystorage 表号="00430" 中文名="电储能" 类别库="交流设备" 类="交流电化学储能">
//  标识  英文标识  中文名称  描述       厂站ID  间隔ID  电压类型ID  电压等级ID  连接点号  状态    投产状态   负荷类型  拓扑着色  拓扑节点  记录所属应用  所在负荷区域  有功正常值  无功正常值  电流正常值  有功上限  无功上限  电流上限   是否参予考核  越限检验标志  等值连接位置  是否边界联络线  切负荷率  有功分配系数  无功分配系数  有功预测值  无功预测值  无功比例系数  是否开断标志  有功值  有功质量码  计算前有功值  有功量测时间  有功量测屏蔽  有功量测权值  无功值  无功质量码  计算前无功值  无功量测时间  无功量测屏蔽  无功量测权值  电流值  电流质量码  计算前电流值  电流量测时间  电流量测屏蔽  电流量测权值  A相电流值  A相电流质量码  A相电流量测时间  B相电流值  B相电流质量码  B相电流量测时间  C相电流值  C相电流质量码  C相电流量测时间  rdf标示  负荷有功下限  负荷无功下限  储电量(绝对值)  储电量质量位  计算前储电量  储电量量测时间  储电量量测屏蔽  储电量权重  充电功率变化率最大值  充电功率最大值  充电功率最小值  放电功率变化率最大值  放电功率最大值  放电功率最小值  储电量最小值(绝对值)  储电量最大值(绝对值)  充电次数最大值  放电次数最大值  充电效率  放电效率  实时效率  日自损耗率  有功设定值  无功设定值  是否可调  是否参与日前调度  是否参与日内调度  是否参与实时调度  故障概率    电压下限  电压上限  电压值  电压质量码  计算前电压值  电压量测时间  电压量测屏蔽  电压量测权值  初始储能容量  结束储能容量  是否允许储能起始SOC不同  储能起始SOC差惩罚系数  当前充电次数  当前放电次数
@  id    code      name      describeb  st_id   bay_id  bv_id       vl_id       nd        status  run_state  ld_type   tpcolor   tpnd      record_app    ld_area       p_nom       q_nom       i_nom       p_max     q_max     amprating  if_exam       chk_lim       position      if_bound        cutp      p_part        q_part        plf         qlf         q_ratio       open_flag     p       p_qual      p_pre         p_time        p_notuse      p_weight      q       q_qual      q_pre         q_time        q_notuse      q_weight      i       i_qual      i_pre         i_time        i_notuse      i_weight      i_a        i_a_qual       i_a_time         i_b        i_b_qual       i_b_time         i_c        i_c_qual       i_c_time         rdf_id   p_min         q_min         soc             soc_qual      soc_pre       soc_time        soc_notuse      soc_weight  rccp_max              recpo_max       recpo_min       rcdp_max              dispo_max       dispo_min       soc_min               soc_max               cn_max          dcn_max         ce        de        eff       slorate     p_set       q_set       regable   da_enable         ro_enable         rt_enable         fault_prob  v_min     v_max     v       v_qual      v_pre         v_time        v_notuse      v_weight      soc0          soc1          store_no_equal           store_penalty          cn_now        dcn_now     
</energystorage>
