<basevoltage 表号="00401" 中文名="电压类型" 类别库="基础数据" 元件库="basevoltage">
//  标识  英文标识  中文名称  电压基准值  电压类型颜色  阻抗基值  电流基值  电压上限  电压下限  电压考核基值  功率考核基值  CA分析方式  总有功出力  总无功出力  总有功负荷  总无功负荷  总有功损耗  总无功损耗  模型所属区域  rdf标示  模型同步标识    是否参与无功电压统计  是否统计网损  下装分区       
@  id    code      name      nomvol      vlcolor       zbase     ibase     hvol      lvol      vbase_kh      sbase_kh      n1_manner   pgen        qgen        pload       qload       ploss       qloss       region_id     rdf_id   replicate_flag  bstatics              bloss         download_region
</basevoltage>

<company 表号="00403" 中文名="电力公司" 类别库="基础数据" 元件库="company">
//  标识  英文标识  中文名称  公司类型   有功发电  有功发电质量码  无功发电  无功发电质量码  有功负荷  有功负荷质量码  无功负荷  无功负荷质量码  有功损耗  有功损耗质量码  无功损耗  无功损耗质量码  有功厂用电  有功厂用电质量码  无功厂用电  无功厂用电质量码  电容器无功  电容器无功质量码  电抗器无功  电抗器无功质量码  有功净输出  有功净输出质量码  无功净输出  无功净输出质量码  用电有功  用电有功质量码  用电无功  用电无功质量码  统调用电有功  统调用电有功质量码  统调用电无功  统调用电无功质量码  统调发电有功  统调发电有功质量码  统调发电无功  统调发电无功质量码  网损率    网损率质量码   SubControlArea表首地址  rdf标示  模型所属区域  模型同步标识    是否参与无功电压统计  是否统计网损  下装分区       
@  id    code      name      cmpy_type  pgen      pgen_qual       qgen      qgen_qual       pload     pload_qual      qload     qload_qual      ploss     ploss_qual      qloss     qloss_qual      paux        paux_qual         qaux        qaux_qual         cap         cap_qual          reac        reac_qual         pint        pint_qual         qint        qint_qual         puse      pused_qual      quse      quse_qual       pdispt_use    pdispt_use_qual     qdispt_use    qdispt_use_qual     pdispt_gen    pdispt_gen_qual     qdispt_gen    qdispt_gen_qual     lossrate  lossrate_qual  oo_subcontrolarea       rdf_id   region_id     replicate_flag  bstatics              bloss         download_region
</company>

<subcontrolarea 表号="00404" 中文名="区域" 类别库="基础数据" 元件库="subcontrolarea">
//  标识  英文标识  中文名称  公司ID   父区域ID   有功发电  有功发电质量码  无功发电  无功发电质量码  有功负荷  有功负荷质量码  无功负荷  无功负荷质量码  有功损耗  有功损耗质量码  无功损耗  无功损耗质量码  有功厂用电  有功厂用电质量码  无功厂用电  无功厂用电质量码  电容器无功  电容器无功质量码  电抗器无功  电抗器无功质量码  有功净输出  有功净输出质量码  无功净输出  无功净输出质量码  用电有功  用电有功质量码  用电无功  用电无功质量码  统调用电有功  统调用电有功质量码  统调用电无功  统调用电无功质量码  统调发电有功  统调发电有功质量码  统调发电无功  统调发电无功质量码  网损率    网损率质量码   频率  频率质量码  SubStation表首地址  rdf标示  在线最大有功出力  在线最小有功出力  在线最大无功出力  在线最小无功出力  在线最大有功负荷  在线最小有功负荷  在线最大无功负荷  在线最小无功负荷  在线有功上旋转备用  在线无功上旋转备用  在线有功下旋转备用  在线无功下旋转备用  有功冷备出力  冷备负荷  应用附加表kid  区域类型   有功正旋备  有功负旋备  无功正备用  无功负备用  有功向上调节备用  有功向下调节备用  正快速备用容量  负快速备用容量  正时段备用   负时段备用   低压电抗投入容量  高压电抗投入容量  低压电容投入容量  CA分析方式  是否排除   事故备用  正时段备用2   负时段备用2   线路负载率    线路负载率质量码   变压器负载率  变压器负载率质量码  发电机负载率  发电机负载率质量码  越限断面个数         断面严重越限时间      断面严重越限次数       断面最大越限程度        平均AGC调节系数    AGC投运率     线路断面指标      变电站指标            发电备用指标          电压指标           频率指标             系统安全指标      系统质量指标       系统综合指标       平均旋转备用率  平均事故备用率  主网电压合格率  电压不合格次数  责任频率合格率  全网最高频率   全网最低频率   责任频率越限时间   母线数     停运母线数  变压器数  停运变压器数  变压器总容量  停运变压器容量  发电机数  停运发电机数  发电机总容量  停运发电机容量  线路数    停运线路数  500kV母线数  500kV停运母线数  220kV母线数  220kV停运母线数  500kV线路数  500kV停运线路数  220kV线路数  220kV停运线路数  是否外网区域  越限检验标志  模型所属区域  模型同步标识    小区号   负荷静特性模型类型  负荷静特性模型参数组  负荷动特性模型类型  负荷动特性模型参数组  感应电动机模型类型  感应电动机模型参数组  形成感应电动机负荷最小值  是否参与无功电压统计  是否统计网损  序列号       单位名称  检修编码  联系人   无功正冷备  下装分区         10min上调节备用  10min下调节备用  30min上调节备用  30min下调节备用  5分钟非旋转备用  10分钟非旋转备用  30分钟非旋转备用
@  id    code      name      cmpy_id  father_id  pgen      pgen_qual       qgen      qgen_qual       pload     pload_qual      qload     qload_qual      ploss     ploss_qual      qloss     qloss_qual      pplant      pplant_qual       qplant      qplant_qual       cap         cap_qual          reac        reac_qual         pint        pint_qual         qint        qint_qual         puse      pused_qual      quse      quse_qual       pdispt_use    pdispt_use_qual     qdispt_use    qdispt_use_qual     pdispt_gen    pdispt_gen_qual     qdispt_gen    qdispt_gen_qual     lossrate  lossrate_qual  freq  freq_qual   oo_substation       rdf_id   gnwmx             gnwmn             gnrmx             gnrmn             ldwmx             ldwmn             ldrmx             ldrmn             unrsvwu             unrsvru             unrsvwd             unrsvrd             gnwcold       ldwcold   auxkid         area_type  p_up        p_dn        q_up        q_dn        p_adjust_up       p_adjust_dn       p_hurry_up      p_hurry_dn      p_minute_up  p_minute_dn  q_lv_rea          q_hv_rea          q_lv_cap          n1_manner   remove_fg  sgby      p_minute_up2  p_minute_dn2  ln_load_rate  ln_load_rate_qual  tr_load_rate  tr_load_rate_qual   gn_load_rate  gn_load_rate_qual   limit_violation_sec  limit_violation_time  limit_violation_times  limit_violation_degree  agc_adjust_coeffi  agc_run_rate  ln_sec_indicator  substation_indicator  generating_indicator  voltage_indicator  frequency_indicator  safety_indicator  quality_indicator  general_indicator  rvsp_rate       avsp_rate       avdp_rate       avdp_num        frequency_rate  max_frequency  min_frequency  frequency_lv_time  bus_total  bus_off     tr_total  tr_off        tr_nom_total  tr_nom_off      gn_total  gn_off        gn_nom_total  gn_nom_off      ln_total  ln_off      bus_total_1  bus_off_1        bus_total_2  bus_off_2        ln_total_1   ln_off_1         ln_total_2   ln_off_2         if_out_net    chk_lmt       region_id     replicate_flag  zone_no  smode               smode_par             dmode               dmode_par             mmode               mmode_par             pmin                      bstatics              bloss         obj_dispidx  dwmc      bm        linkman  qgupcold    download_region  p_agc10min_up    p_agc10min_dn    p_agc30min_up    p_agc30min_dn    p_op5min_rv      p_op10min_rv      p_op30min_rv    
</subcontrolarea>

<substation 表号="00405" 中文名="厂站" 类别库="基础数据" 元件库="substation">
//  标识  英文标识  中文名称  最高电压类型ID  区域ID      厂站类型  厂站编号  厂站状态  接线图名称  是否自动旁路代  是否参与考核  是否参与状态估计  节点数  岛数     所属岛  记录所属应用  有功发电  有功发电质量码  无功发电  无功发电质量码  有功负荷  有功负荷质量码  无功负荷  无功负荷质量码  有功损耗  有功损耗质量码  无功损耗  无功损耗质量码  有功厂用电  有功厂用电质量码  无功厂用电  无功厂用电质量码  电容器无功  电容器无功质量码  电抗器无功  电抗器无功质量码  光字牌值1      光字牌值质量码1  光字牌值2      光字牌值质量码2  VoltageLevel表首地址  PowerTransformer表首地址  MeasPoint表首地址  MeasAnolog表首地址  rdf标示  X坐标   Y坐标   职责区     图形最后入库时间  最大旋转有功出力  最小旋转有功出力  最大旋转无功出力  最小旋转无功出力  厂站在线最小有功负荷  厂站在线最小有功负荷  厂站在线最大无功负荷  厂站冷备有功出力  厂站冷备有功出力  应用附加表kid  有功上旋转备用  无功上旋转备用  有功下旋转备用  无功下旋转备用  有功正旋备  有功负旋备  无功正备用  无功负备用  有功向上调节备用  有功向下调节备用  正快速备用容量  负快速备用容量  正时段备用   负时段备用   低压电抗投入容量  高压电抗投入容量  低压电容投入容量  厂站最大可调出力  厂站最小可调出力  事故备用  额定容量  区域ID(省)   是否参与局部统计      厂站量测质量  正时段备用2   负时段备用2   最小技术出力  特殊接线方式  责任区ID   量测类型   越限检验标志  描述       是否自动对端代  量测评分         频率     频率质量码    频率变化率  频率变化率质量码  模型所属区域  模型同步标识    lfo参与因子  lfo所属群  lfo是否中心  是否安装有FWK  控制站类型  小区号   序列号       检修编码  所属公司  电厂地址  投运日期  退役日期  电厂运行状态  拼音简称  分区ID1      分区ID2      越限光字牌值      越限光字牌状态   越限个数        异常光字牌值    异常光字牌状态  异常个数      事故光字牌值    事故光字牌状态  事故个数      告知光字牌值  告知光字牌状态  告知个数    变位光字牌值      变位光字牌状态   变位个数        五类信号告警值  五类信号告警状态  是否加入仿真计算  无功正冷备  一体化区域号    拼接所属区域  厂站封锁标志   下装分区         10min上调节备用  10min下调节备用  30min上调节备用  30min下调节备用  5分钟非旋转备用  10分钟非旋转备用  30分钟非旋转备用  是否参与拓扑
@  id    code      name      bv_id           subarea_id  st_type   st_no     status    graph_name  if_passby       if_exam       caculate_se       nodes   islands  island  record_app    pgen      pgen_qual       qgen      qgen_qual       pload     pload_qual      qload     qload_qual      ploss     ploss_qual      qloss     qloss_qual      paux        paux_qual         qaux        qaux_qual         cap         cap_qual          reac        reac_qual         light_value_1  light_qual_1     light_value_2  light_qual_2     oo_voltagelevel       oo_powertransformer       oo_measpoint       oo_measanolog       rdf_id   x_coor  y_coor  aor_value  last_graph_time   gnwmx             gnwmn             gnrmx             gnrmn             ldwmx                 ldwmn                 ldrmx                 gnwcold           ldwcold           auxkid         unrsvwu         unrsvru         unrsvwd         unrsvrd         p_up        p_dn        q_up        q_dn        p_adjust_up       p_adjust_dn       p_hurry_up      p_hurry_dn      p_minute_up  p_minute_dn  q_lv_rea          q_hv_rea          q_lv_cap          p_adjust_max      p_adjust_min      sgby      mvarate   subarea_id1  localstatistics_flag  meas_fg       p_minute_up2  p_minute_dn2  pmin_tech     mode_type     resp_area  da_option  chk_lmt       describeb  if_autoaside    meas_eval_score  w_f_val  w_f_val_qual  w_f_dft     w_f_dft_qual      region_id     replicate_flag  lfo_fact     lfo_clus   is_cntr      bfwk           fwk_type    zone_no  obj_dispidx  bm        ssgs      dcdz      tyrq      tyrq1     dcyxzt        name_py   divarea_id1  divarea_id2  over_limit_value  over_limit_qual  over_limit_num  abnormal_value  abnormal_qual   abnormal_num  accident_value  accident_qual   accident_num  notify_value  notify_qual     notify_num  deflection_value  deflection_qual  deflection_num  alarm_value     alarm_qual        issim             qgupcold    dist_region_id  area_name     fac_lock_flag  download_region  p_agc10min_up    p_agc10min_dn    p_agc30min_up    p_agc30min_dn    p_op5min_rv      p_op10min_rv      p_op30min_rv      if_topo     
</substation>

<dms_def_area 表号="12038" 中文名="区域" 类别库="基础数据" 元件库="dms_def_area">
//  标识  英文标识  中文名称  公司ID   父区域ID   区域健康度    解聚合分解系数  当前有功  聚合最大值  聚合最小值  光伏容量  风机容量  可控负荷容量  充电桩容量  储能容量  水电容量  储能电量  储能当前电量  解聚合结果  
@  id    code      name      cmpy_id  father_id  secure_index  disagg_weight   p_real    p_max_agg   p_min_agg   pv_mva    win_mva   ctrld_mva     chst_mva    bat_mva   hyd_mva   bat_kwh   bat_energy    p_set_disagg
</dms_def_area>

<dms_def_bulk 表号="12001" 中文名="配网台区所属馈线信息表" 类别库="基础数据" 元件库="dms_def_bulk">
//  序号  名称  代码  描述   原始ID  厂站ID  区域ID 
@  id    name  code  descr  rdf_id  st_id   area_id
</dms_def_bulk>

<dms_def_feeder 表号="12002" 中文名="配网台区信息表" 类别库="基础数据" 元件库="dms_def_feeder">
//  序号  名称  代码  描述   原始ID  指向source表的关联  总有功功率损耗  馈线总有功功率  有功质量码  计算前有功  有功量测时间  有功量测屏蔽  有功量测权值  馈线总无功功率  无功质量码  计算前无功  无功量测时间  无功量测屏蔽  无功量测权值  台区所属馈线
@  id    name  code  descr  rdf_id  source_id           p_loss          p               p_qual      p_pre       p_time        p_notuse      p_weight      q               q_qual      q_pre       q_time        q_notuse      q_weight      bulk_id     
</dms_def_feeder>

<dms_def_node 表号="12006" 中文名="配网连接节点" 类别库="基础数据" 元件库="ACNode">
//  序号  名称  代码  描述   原始ID  基本电压，关联到电压表  指向馈线表的关联  指向环网柜的关联  A相电压幅值  A相电压幅值质量码  计算前A相电压幅值  A相电压幅值量测时间  A相电压幅值量测屏蔽  A相电压幅值量测权值  B相电压幅值  B相电压幅值质量码  计算前B相电压幅值  B相电压幅值量测时间  B相电压幅值量测屏蔽  B相电压幅值量测权值  C相电压幅值  C相电压幅值质量码  计算前C相电压幅值  C相电压幅值量测时间  C相电压幅值量测屏蔽  C相电压幅值量测权值  A相电压相角量测值  A相电压相角质量码  计算前A相电压相角  A相电压相角量测时间  A相电压相角量测屏蔽  A相电压相角量测权值  B相电压相角量测值  B相电压相角质量码  计算前B相电压相角  B相电压相角量测时间  B相电压相角量测屏蔽  B相电压相角量测权值  C相电压相角量测值  C相电压相角质量码  计算前C相电压相角  C相电压相角量测时间  C相电压相角量测屏蔽  C相电压相角量测权值  AB线电压幅值  AB线电压幅值质量码  计算前AB线电压幅值  AB线电压幅值量测时间  AB线电压幅值量测屏蔽  AB线电压幅值量测权值  BC线电压幅值  BC线电压幅值质量码  计算前BC线电压幅值  BC线电压幅值量测时间  BC线电压幅值量测屏蔽  BC线电压幅值量测权值  CA线电压幅值  CA线电压幅值质量码  计算前CA线电压幅值  CA线电压幅值量测时间  CA线电压幅值量测屏蔽  CA线电压幅值量测权值  AB线电压相角量测值  AB线电压相角质量码  计算前AB线电压相角  AB线电压相角量测时间  AB线电压相角量测屏蔽  AB线电压相角量测权值  BC线电压相角量测值  BC线电压相角质量码  计算前BC线电压相角  BC线电压相角量测时间  BC线电压相角量测屏蔽  BC线电压相角量测权值  CA线电压相角量测值  CA线电压相角质量码  计算前CA线电压相角  CA线电压相角量测时间  CA线电压相角量测屏蔽  CA线电压相角量测权值
@  id    name  code  descr  rdf_id  bv_id                   feeder_id         sg_id             vma          vma_qual           vma_pre            vma_time             vma_notuse           vma_weight           vmb          vmb_qual           vmb_pre            vmb_time             vmb_notuse           vmb_weight           vmc          vmc_qual           vmc_pre            vmc_time             vmc_notuse           vmc_weight           vaa                vaa_qual           vaa_pre            vaa_time             vaa_notuse           vaa_weight           vab                vab_qual           vab_pre            vab_time             vab_notuse           vab_weight           vac                vac_qual           vac_pre            vac_time             vac_notuse           vac_weight           vm_lab        vm_lab_qual         vm_lab_pre          vm_lab_time           vm_lab_notuse         vm_lab_weight         vm_lbc        vm_lbc_qual         vm_lbc_pre          vm_lbc_time           vm_lbc_notuse         vm_lbc_weight         vm_lca        vm_lca_qual         vm_lca_pre          vm_lca_time           vm_lca_notuse         vm_lca_weight         va_lab              va_lab_qual         va_lab_pre          va_lab_time           va_lab_notuse         va_lab_weight         va_lbc              va_lbc_qual         va_lbc_pre          va_lbc_time           va_lbc_notuse         va_lbc_weight         va_lca              va_lca_qual         va_lca_pre          va_lca_time           va_lca_notuse         va_lca_weight       
</dms_def_node>

<dms_def_lnseg 表号="12009" 中文名="配网线段" 类别库="交流设备" 元件库="交流线路">
//  序号  名称  描述   代码  原始ID  指向电压等级表的关联  指向馈线表的关联  指向lnpa表的的关联  额定容量  最大电流     投运状态   零阻抗支路标识  线路长度  线路首端terminal号  线路末端terminal号  线路首端节点号  线路末端节点号  A相状态  B相状态  C相状态  A相自电阻  AB相间电阻  AC相间电阻  BA相间电阻  B相自电阻  BC相间电阻  CA相间电阻  CB相间电阻  C相自电阻  A相自电抗  AB相间电抗  AC相间电抗  BA相间电抗  B相自电抗  BC相间电抗  CA相间电抗  CB相间电抗  C相自电抗  A相自电导  AB相间电导  AC相间电导  BA相间电导  B相自电导  BC相间电导  CA相间电导  CB相间电导  C相自电导  A相自电纳  AB相间电纳  AC相间电纳  BA相间电纳  B相自电纳  BC相间电纳  CA相间电纳  CB相间电纳  C相自电纳  A相对地电导  B相对地电导  C相对地电导  A相对地电纳  B相对地电纳  C相对地电纳
@  id    name  descr  code  rdf_id  bv_id                 feeder_id         para_id             mva       max_current  run_state  iszero          length    iterminal_id        zterminal_id        inode_id        znode_id        pha      phb      phc      raa        rab         rac         rba         rbb        rbc         rca         rcb         rcc        xaa        xab         xac         xba         xbb        xbc         xca         xcb         xcc        gaa        gab         gac         gba         gbb        gbc         gca         gcb         gcc        baa        bab         bac         bba         bbb        bbc         bca         bcb         bcc        gga          ggb          ggc          bga          bgb          bgc        
</dms_def_lnseg>

<dms_def_lnseg_dot 表号="12010" 中文名="配网线段端点" 类别库="交流设备" 元件库="交流节点">
//  序号  名称  描述   代码  原始ID  指向node表的关联  A相有功功率  A相有功质量码  计算前A相有功  A相有功量测时间  A相有功量测屏蔽  A相有功量测权值  B相有功功率  B相有功质量码  计算前B相有功  B相有功量测时间  B相有功量测屏蔽  B相有功量测权值  C相有功功率  C相有功质量码  计算前C相有功  C相有功量测时间  C相有功量测屏蔽  C相有功量测权值  A相无功功率  A相无功质量码  计算前A相无功  A相无功量测时间  A相无功量测屏蔽  A相无功量测权值  B相无功功率  B相无功质量码  计算前B相无功  B相无功量测时间  B相无功量测屏蔽  B相无功量测权值  C相无功功率  C相无功质量码  计算前C相无功  C相无功量测时间  C相无功量测屏蔽  C相无功量测权值  A相电流幅值  A相电流幅值质量码  计算前A相电流幅值  A相电流幅值量测时间  A相电流幅值量测屏蔽  A相电流幅值量测权值  B相电流幅值  B相电流幅值质量码  计算前B相电流幅值  B相电流幅值量测时间  B相电流幅值量测屏蔽  B相电流幅值量测权值  C相电流幅值  C相电流幅值质量码  计算前C相电流幅值  C相电流幅值量测时间  C相电流幅值量测屏蔽  C相电流幅值量测权值  A相电流相角  A相电流相角质量码  计算前A相电流相角  A相电流相角量测时间  A相电流相角量测屏蔽  A相电流相角量测权值  B相电流相角  B相电流相角质量码  计算前B相电流相角  B相电流相角量测时间  B相电流相角量测屏蔽  B相电流相角量测权值  C相电流相角  C相电流相角质量码  计算前C相电流相角  C相电流相角量测时间  C相电流相角量测屏蔽  C相电流相角量测权值  A相电压幅值  A相电压幅值质量码  计算前A相电压幅值  A相电压幅值量测时间  A相电压幅值量测屏蔽  A相电压幅值量测权值  B相电压幅值  B相电压幅值质量码  计算前B相电压幅值  B相电压幅值量测时间  B相电压幅值量测屏蔽  B相电压幅值量测权值  C相电压幅值  C相电压幅值质量码  计算前C相电压幅值  C相电压幅值量测时间  C相电压幅值量测屏蔽  C相电压幅值量测权值  A相电压相角  A相电压相角质量码  计算前A相电压相角  A相电压相角量测时间  A相电压相角量测屏蔽  A相电压相角量测权值  B相电压相角  B相电压相角质量码  计算前B相电压相角  B相电压相角量测时间  B相电压相角量测屏蔽  B相电压相角量测权值  C相电压相角  C相电压相角质量码  计算前C相电压相角  C相电压相角量测时间  C相电压相角量测屏蔽  C相电压相角量测权值  三相有功功率  三相有功质量码  计算前三相有功  三相有功量测时间  三相有功量测屏蔽  三相有功量测权值  三相无功功率  三相无功质量码  计算前三相无功  三相无功量测时间  三相无功量测屏蔽  三相无功量测权值
@  id    name  descr  code  rdf_id  node_id           pa           pa_qual        pa_pre         pa_time          pa_notuse        pa_weight        pb           pb_qual        pb_pre         pb_time          pb_notuse        pb_weight        pc           pc_qual        pc_pre         pc_time          pc_notuse        pc_weight        qa           qa_qual        qa_pre         qa_time          qa_notuse        qa_weight        qb           qb_qual        qb_pre         qb_time          qb_notuse        qb_weight        qc           qc_qual        qc_pre         qc_time          qc_notuse        qc_weight        ima          ima_qual           ima_pre            ima_time             ima_notuse           ima_weight           imb          imb_qual           imb_pre            imb_time             imb_notuse           imb_weight           imc          imc_qual           imc_pre            imc_time             imc_notuse           imc_weight           iaa          iaa_qual           iaa_pre            iaa_time             iaa_notuse           iaa_weight           iab          iab_qual           iab_pre            iab_time             iab_notuse           iab_weight           iac          iac_qual           iac_pre            iac_time             iac_notuse           iac_weight           vma          vma_qual           vma_pre            vma_time             vma_notuse           vma_weight           vmb          vmb_qual           vmb_pre            vmb_time             vmb_notuse           vmb_weight           vmc          vmc_qual           vmc_pre            vmc_time             vmc_notuse           vmc_weight           vaa          vaa_qual           vaa_pre            vaa_time             vaa_notuse           vaa_weight           vab          vab_qual           vab_pre            vab_time             vab_notuse           vab_weight           vac          vac_qual           vac_pre            vac_time             vac_notuse           vac_weight           p             p_qual          p_pre           p_time            p_notuse          p_weight          q             q_qual          q_pre           q_time            q_notuse          q_weight        
</dms_def_lnseg_dot>

<dms_def_trfm 表号="12012" 中文名="配网变压器" 类别库="交流设备" 元件库="双绕组变压器">
//  序号  名称  描述   代码  原始ID  指向馈线表的关联  指向变压器参数类型表的的关联  额定容量  最大电流     投运状态   A相状态  B相状态  C相状态  空载损耗  额定负载损耗
@  id    name  descr  code  rdf_id  feeder_id         para_id                       mva       max_current  run_state  pha      phb      phc      p0        pk          
</dms_def_trfm>

<dms_def_trwd 表号="12013" 中文名="配网绕组" 类别库="交流设备" 元件库="变压器绕组">
//  序号  名称  描述   代码  原始ID  指向主变表的关联  指向馈线表的关联  额定容量  最大电流     高中低端标识  连接组别  A相状态  B相状态  C相状态  A相电阻  B相电阻  C相电阻  A相电抗  B相电抗  C相电抗  A相对地电导  B相对地电导  C相对地电导  A相对地电纳  B相对地电纳  C相对地电纳  指向电压类型表  节点号   A相有功功率  A相有功质量码  计算前A相有功  A相有功量测时间  A相有功量测屏蔽  A相有功量测权值  B相有功功率  B相有功质量码  计算前B相有功  B相有功量测时间  B相有功量测屏蔽  B相有功量测权值  C相有功功率  C相有功质量码  计算前C相有功  C相有功量测时间  C相有功量测屏蔽  C相有功量测权值  A相无功功率  A相无功质量码  计算前A相无功  A相无功量测时间  A相无功量测屏蔽  A相无功量测权值  B相无功功率  B相无功质量码  计算前B相无功  B相无功量测时间  B相无功量测屏蔽  B相无功量测权值  C相无功功率  C相无功质量码  计算前C相无功  C相无功量测时间  C相无功量测屏蔽  C相无功量测权值  A相电流幅值  A相电流幅值质量码  计算前A相电流幅值  A相电流幅值量测时间  A相电流幅值量测屏蔽  A相电流幅值量测权值  B相电流幅值  B相电流幅值质量码  计算前B相电流幅值  B相电流幅值量测时间  B相电流幅值量测屏蔽  B相电流幅值量测权值  C相电流幅值  C相电流幅值质量码  计算前C相电流幅值  C相电流幅值量测时间  C相电流幅值量测屏蔽  C相电流幅值量测权值  A相电流相角  A相电流相角质量码  计算前A相电流相角  A相电流相角量测时间  A相电流相角量测屏蔽  A相电流相角量测权值  B相电流相角  B相电流相角质量码  计算前B相电流相角  B相电流相角量测时间  B相电流相角量测屏蔽  B相电流相角量测权值  C相电流相角  C相电流相角质量码  计算前C相电流相角  C相电流相角量测时间  C相电流相角量测屏蔽  C相电流相角量测权值  A相电压幅值  A相电压幅值质量码  计算前A相电压幅值  A相电压幅值量测时间  A相电压幅值量测屏蔽  A相电压幅值量测权值  B相电压幅值  B相电压幅值质量码  计算前B相电压幅值  B相电压幅值量测时间  B相电压幅值量测屏蔽  B相电压幅值量测权值  C相电压幅值  C相电压幅值质量码  计算前C相电压幅值  C相电压幅值量测时间  C相电压幅值量测屏蔽  C相电压幅值量测权值  A相电压相角  A相电压相角质量码  计算前A相电压相角  A相电压相角量测时间  A相电压相角量测屏蔽  A相电压相角量测权值  B相电压相角  B相电压相角质量码  计算前B相电压相角  B相电压相角量测时间  B相电压相角量测屏蔽  B相电压相角量测权值  C相电压相角  C相电压相角质量码  计算前C相电压相角  C相电压相角量测时间  C相电压相角量测屏蔽  C相电压相角量测权值  三相有功功率  三相有功质量码  计算前三相有功  三相有功量测时间  三相有功量测屏蔽  三相有功量测权值  三相无功功率  三相无功质量码  计算前三相无功  三相无功量测时间  三相无功量测屏蔽  三相无功量测权值  空载损耗  额定负载损耗
@  id    name  descr  code  rdf_id  trfm_id           feeder_id         mva       max_current  pos           contype   pha      phb      phc      raa      rbb      rcc      xaa      xbb      xcc      gda          gdb          gdc          bda          bdb          bdc          bv_id           node_id  pa           pa_qual        pa_pre         pa_time          pa_notuse        pa_weight        pb           pb_qual        pb_pre         pb_time          pb_notuse        pb_weight        pc           pc_qual        pc_pre         pc_time          pc_notuse        pc_weight        qa           qa_qual        qa_pre         qa_time          qa_notuse        qa_weight        qb           qb_qual        qb_pre         qb_time          qb_notuse        qb_weight        qc           qc_qual        qc_pre         qc_time          qc_notuse        qc_weight        ima          ima_qual           ima_pre            ima_time             ima_notuse           ima_weight           imb          imb_qual           imb_pre            imb_time             imb_notuse           imb_weight           imc          imc_qual           imc_pre            imc_time             imc_notuse           imc_weight           iaa          iaa_qual           iaa_pre            iaa_time             iaa_notuse           iaa_weight           iab          iab_qual           iab_pre            iab_time             iab_notuse           iab_weight           iac          iac_qual           iac_pre            iac_time             iac_notuse           iac_weight           vma          vma_qual           vma_pre            vma_time             vma_notuse           vma_weight           vmb          vmb_qual           vmb_pre            vmb_time             vmb_notuse           vmb_weight           vmc          vmc_qual           vmc_pre            vmc_time             vmc_notuse           vmc_weight           vaa          vaa_qual           vaa_pre            vaa_time             vaa_notuse           vaa_weight           vab          vab_qual           vab_pre            vab_time             vab_notuse           vab_weight           vac          vac_qual           vac_pre            vac_time             vac_notuse           vac_weight           p             p_qual          p_pre           p_time            p_notuse          p_weight          q             q_qual          q_pre           q_time            q_notuse          q_weight          p0        pk          
</dms_def_trwd>

<dms_def_load 表号="12020" 中文名="配网负荷" 类别库="交流设备" 元件库="交流负荷+">
//  标识  中文名称  英文标识  描述   rdf标示  投运状态   A相位存在状态  B相位存在状态  C相位存在状态  指向电压等级表的关联  指向馈线表的关联  节点号   负荷端子      Y或D型连接/ZIP三种负荷类型  恒阻抗负荷百分占比  恒流负荷百分占比  恒功率负荷百分占比  A相电压量测值  B相电压量测值  C相电压量测值  A相电压量测值  A相电压幅值质量码  计算前A相电压幅值  A相电压幅值量测时间  A相电压幅值量测屏蔽  A相电压幅值量测权值  B相电压量测值  B相电压幅值质量码  计算前B相电压幅值  B相电压幅值量测时间  B相电压幅值量测屏蔽  B相电压幅值量测权值  C相电压量测值  C相电压幅值质量码  计算前C相电压幅值  C相电压幅值量测时间  C相电压幅值量测屏蔽  C相电压幅值量测权值  A相相角量测值  A相电压相角质量码  计算前A相电压相角  A相电压相角量测时间  A相电压相角量测屏蔽  A相电压相角量测权值  B相相角量测值  B相电压相角质量码  计算前B相电压相角  B相电压相角量测时间  B相电压相角量测屏蔽  B相电压相角量测权值  C相相角量测值  C相电压相角质量码  计算前C相电压相角  C相电压相角量测时间  C相电压相角量测屏蔽  C相电压相角量测权值  A相有功功率量测值  A相有功质量码  计算前A相有功  A相有功量测时间  A相有功量测屏蔽  A相有功量测权值  B相有功功率量测值  B相有功质量码  计算前B相有功  B相有功量测时间  B相有功量测屏蔽  B相有功量测权值  C相有功功率量测值  C相有功质量码  计算前C相有功  C相有功量测时间  C相有功量测屏蔽  C相有功量测权值  AB线有功功率量测值  AB线有功质量码  计算前AB线有功  AB线有功量测时间  AB线有功量测屏蔽  AB线有功量测权值  BC线有功功率量测值  BC线有功质量码  计算前BC线有功  BC线有功量测时间  BC线有功量测屏蔽  BC线有功量测权值  CA线有功功率量测值  CA线有功质量码  计算前CA线有功  CA线有功量测时间  CA线有功量测屏蔽  CA线有功量测权值  正常有功值  A相正常有功值  B相正常有功值  C相正常有功值  A相有功功率设定值  B相有功功率设定值  C相有功功率设定值  AB线有功功率设定值  BC线有功功率设定值  CA线有功功率设定值  A相无功功率量测值  A相无功质量码  计算前A相无功  A相无功量测时间  A相无功量测屏蔽  A相无功量测权值  B相无功功率量测值  B相无功质量码  计算前B相无功  B相无功量测时间  B相无功量测屏蔽  B相无功量测权值  C相无功功率量测值  C相无功质量码  计算前C相无功  C相无功量测时间  C相无功量测屏蔽  C相无功量测权值  AB线无功功率量测值  AB线无功质量码  计算前AB线无功  AB线无功量测时间  AB线无功量测屏蔽  AB线无功量测权值  BC线无功功率量测值  BC线无功质量码  计算前BC线无功  BC线无功量测时间  BC线无功量测屏蔽  BC线无功量测权值  CA线无功功率量测值  CA线无功质量码  计算前CA线无功  CA线无功量测时间  CA线无功量测屏蔽  CA线无功量测权值  正常无功值  A相正常无功值  B相正常无功值  C相正常无功值  A相无功功率设定值  B相无功功率设定值  C相无功功率设定值  AB线无功功率设定值  BC线无功功率设定值  CA线无功功率设定值  三相有功功率  三相有功质量码  计算前三相有功  三相有功量测时间  三相有功量测屏蔽  三相有功量测权值  三相无功功率  三相无功质量码  计算前三相无功  三相无功量测时间  三相无功量测屏蔽  三相无功量测权值  额定容量  最大有功  最小有功  最大无功  最小无功  调节成本（元/MWh）
@  id    name      code      descr  rdf_id   run_state  pha            phb            phc            bv_id                 feeder_id         node_id  iterminal_id  contype                     kz                  ki                kp                  rated_u        rated_p        rated_q        vma            vma_qual           vma_pre            vma_time             vma_notuse           vma_weight           vmb            vmb_qual           vmb_pre            vmb_time             vmb_notuse           vmb_weight           vmc            vmc_qual           vmc_pre            vmc_time             vmc_notuse           vmc_weight           vaa            vaa_qual           vaa_pre            vaa_time             vaa_notuse           vaa_weight           vab            vab_qual           vab_pre            vab_time             vab_notuse           vab_weight           vac            vac_qual           vac_pre            vac_time             vac_notuse           vac_weight           pa                 pa_qual        pa_pre         pa_time          pa_notuse        pa_weight        pb                 pb_qual        pb_pre         pb_time          pb_notuse        pb_weight        pc                 pc_qual        pc_pre         pc_time          pc_notuse        pc_weight        pab                 pab_qual        pab_pre         pab_time          pab_notuse        pab_weight        pbc                 pbc_qual        pbc_pre         pbc_time          pbc_notuse        pbc_weight        pca                 pca_qual        pca_pre         pca_time          pca_notuse        pca_weight        p_nom       pa_nom         pb_nom         pc_nom         pa_set             pb_set             pc_set             pab_set             pbc_set             pca_set             qa                 qa_qual        qa_pre         qa_time          qa_notuse        qa_weight        qb                 qb_qual        qb_pre         qb_time          qb_notuse        qb_weight        qc                 qc_qual        qc_pre         qc_time          qc_notuse        qc_weight        qab                 qab_qual        qab_pre         qab_time          qab_notuse        qab_weight        qbc                 qbc_qual        qbc_pre         qbc_time          qbc_notuse        qbc_weight        qca                 qca_qual        qca_pre         qca_time          qca_notuse        qca_weight        q_nom       qa_nom         qb_nom         qc_nom         qa_set             qb_set             qc_set             qab_set             qbc_set             qca_set             p             p_qual          p_pre           p_time            p_notuse          p_weight          q             q_qual          q_pre           q_time            q_notuse          q_weight          mva       p_max     p_min     q_max     q_min     adjust_cost       
</dms_def_load>


<dms_def_qs 表号="12034" 中文名="配网隔离开关" 类别库="交流设备" 元件库="交流开关">
//  序号  名称  代码  描述   原始ID  指向馈线表的关联  指向电压等级表的关联  隔离开关首端节点号  隔离开关末端节点号  隔离开关首端terminal号  隔离开关末端terminal号  指向隔离开关型号表的关联  A相状态  B相状态  C相状态  投运状态   闭合状态  闭合状态质量码  闭合状态计算前闭合状态  闭合状态量测时间  闭合状态量测屏蔽  A相闭合状态  A相闭合状态质量码  A相闭合状态计算前A相闭合状态  A相闭合状态量测时间  A相闭合状态量测屏蔽  B相闭合状态  B相闭合状态质量码  B相闭合状态计算前B相闭合状态  B相闭合状态量测时间  B相闭合状态量测屏蔽  C相闭合状态  C相闭合状态质量码  C相闭合状态计算前C相闭合状态  C相闭合状态量测时间  C相闭合状态量测屏蔽  A相电流幅值  A相电流质量码  A相电流计算前A相电流  A相电流量测时间  A相电流量测屏蔽  A相电流量测权值  B相电流幅值  B相电流质量码  B相电流计算前B相电流  B相电流量测时间  B相电流量测屏蔽  B相电流量测权值  C相电流幅值  C相电流质量码  C相电流计算前C相电流  C相电流量测时间  C相电流量测屏蔽  C相电流量测权值  最大潮流   
@  id    name  code  descr  rdf_id  feeder_id         bv_id                 inode_id            znode_id            iterminal_id            zterminal_id            para_id                   pha      phb      phc      run_state  closed    closed_qual     closed_pre              closed_time       closed_notuse     ca           ca_qual            ca_pre                        ca_time              ca_notuse            cb           cb_qual            cb_pre                        cb_time              cb_notuse            cc           cc_qual            cc_pre                        cc_time              cc_notuse            ima          ima_qual       ima_pre               ima_time         ima_notuse       ima_weight       imb          imb_qual       imb_pre               imb_time         imb_notuse       imb_weight       imc          imc_qual       imc_pre               imc_time         imc_notuse       imc_weight       max_current
</dms_def_qs>